### ISSUE TITLE
return string

### ISSUE THREAD

**Issue by jgoeders** [byu-cpe/ygrader#25]
When my callback function runs into a problem, I return the string “something wrong”.  When the ygrader goes back through the csv file I think that it only looks for number.  It crashes when it encounters the string.

PS C:\Users\schultz> c:
PS C:\Users\schultz> cd c:/sms/classes/ee340/F22/Proj/P1
PS C:\sms\classes\ee340\F22\Proj\P1> & C:/Users/schultz/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/sms/classes/ee340/F22/Proj/P1/P1.py
Running grader for P1 
104 students need to be graded. 
Traceback (most recent call last):
  File "c:\sms\classes\ee340\F22\Proj\P1\P1.py", line 177, in <module>
    grader.run()
  File "C:\Users\schultz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ygrader\grader.py", line 439, in run
r.py", line 450, in _run_grading
    num_group_members_need_grade_per_item = [  File "C:\Users\schultz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ygrader\grader.py", line 451, in <listcomp>
    item.num_grades_needed(row) for item in self.items  File "C:\Users\schultz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ygrader\grading_item.py", line 212, in num_grades_needed   
    if numpy.isnan(grade):TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
PS C:\sms\classes\ee340\F22\Proj\P1>

**Comment by jgoeders** [comment]
Fixed in 1.1.14
